### ISSUE TITLE
dangling node

### ISSUE THREAD

**Issue by cecileane** [jjustison/SiPhyNetwork#5]
sorry, one more report 😮 !
I came across networks that have non-leaf nodes without any children. That's rare, but here is an example:

```r
require(SiPhyNetwork)
inheritance_fxn = make.beta.draw(10,10)
hybridproportions = c(0.5,0.25,0.25)
set.seed(5282)
net <- sim.bdh.taxa.ssa(n=17, numbsim=1,
    lambda=1,mu=0.2, nu=0.8, hybprops=hybridproportions,
    hyb.inher.fxn = inheritance_fxn)[[1]]
write.net(net, digits=1)
```

the output is a mouthful, sorry:

```
"(((((((t12:0.1,#H87:0.04::0.566817808665801):0.07,#H69:0::0.363177806287171):0.4,((((((t5:0.04,():0):0.2)#H75:0::0.560043980278853,#H77:0.01::0.356749669774551):0.1,((t18:0.1,#H85:0::0.679805427150224):0.02,#H84:0::0.41641402604163):0.2):0.1)#H46:0.2::0.439835130806992)#H43:0::0.446440230563991):0.02,#H40:0::0.452335033482829):0.2,#H27:0::0.626470441974728):0.6,((((((((((t1:0.2,#H75:0::0.439956019721147):0.004)#H56:0.1::0.366278800991607,#H55:0::0.500612545096176):0.09,#H46:0::0.560164869193008):0.03,(((((((#H82:0.03::0.419661471950185)#H81:0.06::0.411872637536133,#H79:0::0.373315241205891):0.009)#H77:0.003::0.643250330225449)#H58:0.1::0.644974840787198)#H57:0.02::0.51611249556549)#H55:0::0.499387454903824,#H57:0.02::0.48388750443451):0.1):0.2,(((#H42:0.07::0.265304329797207)#H40:0.02::0.547664966517171,#H38:0::0.452173412265279):0.004,(((#H62:0::0.408854680385383,#H58:0.09::0.355025159212802):0.3)#H42:0.06::0.734695670202793)#H37:0.03::0.421707616423641):0.05):0.04,#H31:0::0.475380353357758):0.08,(((((((((((t16:0.04,#H98:0.03::0.532697954851926):0.06)#H87:0.006::0.433182191334199)#H85:0.02::0.320194572849776,(t2:0.1)#H84:0::0.58358597395837):0.08,#H73:0::0.512554982986711):0.004,#H56:0::0.633721199008393):0.04,((t20:0.05,#H88:0::0.367932348319471):0.05,(((t11:0.02,t24:0.02):0.06,(t9:0.07)#H95:0::0.54866966512444):0.02)#H90:0::0.356200187546517):0.2):0.04,((((t17:0.01,t26:0.01,#H94:0::0.655539860002413)#H98:0.06::0.467302045148074,#H95:0::0.45133033487556):0.1,(((t6:0.05)#H88:0.06::0.632067651680529)#H82:0.08::0.580338528049815)#H79:0::0.626684758794109):0.1)#H62:0::0.591145319614617):0.08,#H48:0::0.444746978914219):0.3,(#H37:0.03::0.578292383576359)#H38:0::0.547826587734721):0.2)#H27:0::0.373529558025272):0.3,(t14:0.1,(((((t4:0.2)#H73:0::0.487445017013289,#H72:0.03::0.576699910918535):0.1,t22:0.3):0.3,(t27:0.4)#H48:0.2::0.555253021085781):0.2)#H31:0::0.524619646642242):0.4):0.3,(((((t3:0.03)#H94:0.06::0.344460139997587)#H92:0.01::0.338453967866981,#H90:0::0.643799812453483):0.1,(((#H81:0::0.588127362463867,#H92:0.05::0.661546032133019):0.05)#H72:0.03::0.423300089081465)#H69:0::0.636822193712829):0.4,#H43:0::0.553559769436009):0.8):0.01):0.8);"
```

This newick description contains this: `...():0):0.2)#H75:...` with a pair of parentheses that has nothing inside.
I first stumbled across a network that had this: `...()#H115:0::0.4...` (I can reproduce it but as part of a larger julia script. I'm not sending it, but I can serve as tester!)

By the way, in `write.net` it looks like the `digits` option only applies to edge lengths, not γs (feature?)

Should I use some option to prune these dangling nodes? It makes sense that they would appear in the original network, but not in the reconstructed network. So perhaps I'm missing a step to get the reconstructed network.

**Comment by jjustison** [comment]
I think this was an issue with code I implemented to fix the issue #1.  It involves reassigning some node numbers and it looks like I missed a place where reassignment needs to occur. I fixed this and haven't seen the dangling node issue after doing some simulations so I think this is where things went awry. 

I suppose this is good motivation to get unit tests up and running soon as that probably would've been caught :see_no_evil:. Thanks for the patience and reporting as you're playing around with the package!

Also, if you want to be working with reconstructed phylogenies you can either set `complete=FALSE` in the simulation function or do it post-hoc with `reconstructedNetwork()`

**Comment by jjustison** [comment]
Also made it so the `digits` argument touches γs

**Comment by cecileane** [comment]
Thank you!! :tada:

yes, unit tests take a lot of time to develop (and set up so they run automatically etc. When I had to move testing from travis CI to GitHub actions, that was painful). But it's so cool to catch errors before they can affect me or others.
