### ISSUE TITLE
extended newick format

### ISSUE THREAD

**Issue by crsl4** [jjustison/SiPhyNetwork#6]
This is a minor thing. I got the parenthetical format below from `SiPhyNetwork`:
```
((((t8:0.4681991291,((t4:0.1122732353,#H34:0::0.9899097874):0.1481915801,#H32:0::0.728598428):0.2077343137):1.01928697,((t10:0.6260437678,(t12:0.625354073,t7:0.625354073):0.0006896948131):0.3308102357,((t13:0.1122732353,(t15:0.1122732353)#H34:0::0.01009021257):0.334506684,t1:0.4467799193):0.5100740842):0.5306320959):0.5266602863,(((t3:0.6118126485,(t2:0.2604648154,(t5:0.2604648154)#H32:0::0.271401572):0.3513478331):0.04918772583,(t11:0.4833606604,t9:0.4833606604):0.1776397139):1.266528995,(t14:1.855881859,t6:1.855881859):0.07164751056):0.086617016):0.5254422314);
```
and it seems to violate a (rather minor) formatting convention on `#H32`. Namely, the leaf associated to `#H32` should correspond to the minor hybrid edge by convention. But in this case, it seems that the leaf is connected to the major hybrid edge: `#H32:0::0.728598428` because gamma>0.5 whereas the internal node associated to `#H32` corresponds to the minor hybrid edge `(t5:0.2604648154)#H32:0::0.271401572` because gamma<0.5 but by convention it should be associated to the major hybrid edge. Maybe this is confusing to explain here and this is not important in any way, so feel free to ignore!

**Comment by jjustison** [comment]
To make sure I'm understanding the issue, I'm going to try and paraphrase it with an example. Let's say we have the following network:

![simple_net](https://user-images.githubusercontent.com/19258474/126668688-3b597075-dae5-450a-bcf5-0d2c2ab9449c.png)

For this network we could have the following parenthetical formats:

**((A:2,(B:1)#H1:1::0.6):1,(C:2,#H1:1::0.4):1);**
or
**((A:2,#H1:1::0.6):1,(C:2,(B:1)#H1:1::0.4):1);**

You'd say that the first representation is more correct because the leaf for `#H1` is associated with the edge that has gamma=0.4 while the internal node for `#H1` is associated with the edge that has gamma=0.6.

**Comment by crsl4** [comment]
yes, this is what I mean! As I mention, this is a minor convention thing, so it does not make any real differences, but it tends to be assumed that the edge you detach to create the leaf #H1 is the corresponding to the minor hybrid edge.

**Comment by jjustison** [comment]
I've primarily been referencing  the [Cardona 2008](https://doi.org/10.1186/1471-2105-9-532) paper and the [Overview of Rich Newick Strings](https://wiki.rice.edu/confluence/download/attachments/5216841/RichNewick-2012-02-16.pdf?version=1&modificationDate=1330535426168&api=v2) for convention and it seems like either representation is okay. Although I now see in your [PhyloNetworks](https://doi.org/10.1093/molbev/msx235) there is the distinction of minor and major edges being different in parenthetical format.

I think adding correctly representing major/minor edges *should* be relatively straightforward with the swapping of a few edges before creating the string. I can try to tackle this after I finish moving houses in early August.

**Comment by crsl4** [comment]
Yes! Both are correct. When I was implementing PhyloNetworks, I read that the minor hybrid edge as the leaf was the convention (even when both are correct), so that's what I did. I will search for the reference! But as I said, this is really not a big deal as both parenthetical formats represent the same network.

**Comment by crsl4** [comment]
BTW I found that mainly the plotting devices struggle with this convention.

**Comment by crsl4** [comment]
This is the same network of the parenthetical format above drawn in R with the two different conventions: left "R network" is the one we got from `SiPhyNetwork` (leaf with major edge) and center "Julia network" is the one with the `PhyloNetworks` convention (leaf with minor edge). Both are indeed the same network, but the blue edge that represents the minor hybrid edge is chosen to be a different edge in each plot. The third plot (right) can be ignored as this is just the network on parenthetical format for HybridLambda.

![image](https://user-images.githubusercontent.com/8419800/126782152-92e7a6d1-8d02-4897-bcdb-beb4c8cc7fc2.png)

**Comment by jjustison** [comment]
Minor and Major hybrid edges should now use the convention  mentioned when written in Newick format
