### ISSUE TITLE
write.net fails when the network is a tree

### ISSUE THREAD

**Issue by cecileane** [jjustison/SiPhyNetwork#7]
We ran into another kind of error, here is a reproducible example:
```r
> set.seed(32)
> net <- sim.bdh.taxa.ssa(n=4, numbsim=1,
+     lambda=1, mu=0.2, nu=0.3, hybprops=c(0.5,0.25,0.25),
+     hyb.rate.fxn = gen_dist_fxn, hyb.inher.fxn = make.beta.draw(2,2), complete=FALSE)[[1]]
> write.net(net, tol=1e-12)
Error in x$reticulation[i, 2] : subscript out of bounds
```

This seems to be caused by the network being a tree:
```r
> net$reticulation
     from to
> net$inheritance
numeric(0)
```

**Comment by jjustison** [comment]
Hello, thanks for the report. To reproduce the network for testing, how are you specifying `gen_dist_fxn`?

This is a peculiar bug. From some initial testing, it seems to affect only networks that are coerced to be treelike when removing extinct tips and their associated hybrid edges (done above by setting `complete=F`) but not complete networks that just had no hybridization events in the first place.  I'll look into this this weekend

**Comment by cecileane** [comment]
Oh I am sorry, that was missing:
```r
gen_dist_fxn = make.stepwise(probs = c(1,0),distances = c(0.75,Inf))
set.seed(32)
net <- sim.bdh.taxa.ssa(n=4, numbsim=1,
    lambda=1, mu=0.2, nu=0.3, hybprops=c(0.5,0.25,0.25),
    hyb.rate.fxn = gen_dist_fxn, hyb.inher.fxn = make.beta.draw(2,2), complete=FALSE)[[1]]
write.net(net, tol=1e-12)
```

Yes, we also noticed that the bug went away with `complete=TRUE` (or at least, that the bug didn't show up among a few thousand simulations).

**Comment by laufran** [comment]
For what it's worth, for some seeds, I get an error with write.net even if `complete=TRUE`.

Here's an example:
```
inheritance_fxn = make.beta.draw(10,10)
gen_dist_fxn = make.stepwise(probs = c(1,0),distances = c(0.75,Inf))
hybridproportions = c(0.5,0.25,0.25)

set.seed(2073)
net = sim.bdh.taxa.ssa(n=17, numbsim=1,
            lambda=1, mu=0.2, nu=0.3, hybprops=hybridproportions,
            hyb.rate.fxn = gen_dist_fxn, hyb.inher.fxn = inheritance_fxn, complete = TRUE)
write.net(net, tol=1e-12)
```

Which gives me the error:
```
Error: $ operator is invalid for atomic vectors 
Traceback:
3. e2p(phy[[i]]) 
2. w.tree(phy = net, file = file, append = append, digits = digits, tree.names = tree.names, tol) 
1. write.net(net, tol = 1e-12)
```

**Comment by jjustison** [comment]
@cecileane So I think I fixed the issue you were having. After having hybrid edges but then removing them all by taking the reconstructed networks, the `$inheritance` part of the network becomes a zero length vector whereas networks with no hybridizations have `$inheritance` as `NULL`. I wasn't properly checking this earlier

**Comment by jjustison** [comment]
@laufran Thanks for the additional reporting on this, its something I'd not even considered but is a natural product of the simulations! So it seems that this error is a bit different than the one Cecile mentioned. From the example you provided, it looks like the network  simulated is a `0`, this means that the network went extinct before reaching 17 species in this case. This isn't super intuitive behavior and brings up a question about how to deal with cases where we run simulations but for one reason or another they don't return phylogenies. I can think of a two possible solutions:

1.  have `write.net()` check for non-phylogenies in the list and not write those to file accordingly
2.  add a `condition` argument to the 3  `sim.bdh` style functions that conditions a valid simulation on it not being extinct or some other criteria (e.g. more than X tips, having at least Y reticulations, etc)

I think the latter is perhaps a more complete solution but adds another argument to the already argument-rich functions. From a user perspective would either of these be more ideal?

In the meantime while I ponder how to approach the issue, you can filter out non-phylogenies from your simulations by doing:
```
true_nets<-net[unlist(lapply(net, function(x) 'phylo' %in% class(x)))]
```

**Comment by cecileane** [comment]
wonderful, it fixed the issue, thank you so much @jjustison !

**Comment by cecileane** [comment]
I think it's fine to return an empty network, provided that you update the documentation to say that the simulation runs either either the required number of taxa is obtained, or the network goes extinct. And perhaps return `FALSE` instead of 0 if the network goes extinct, because that might facilitate the filtering of empty networks.
Leaving extinct networks could potentially facilitate the estimation of the extinction probability, which is a necessary quantify to calculate the *conditional* likelihood. So extinct networks might be useful down the road --else the number of simulated networks that were needed before the first one with the required (non-zero) number of taxa. Eliminating either information could lose precious information to do later conditioning.

**Comment by jjustison** [comment]
Sorry, I tried to address issue #6 in the last commit too but it seems to be causing more issues. The code above should work now

**Comment by jjustison** [comment]
Also thanks for the discussion above about conditioning phylogenies. I think I'll go with your suggestion of updating the documentation to more explicitly mention the types of outcomes that could come from simulation. 

I was thinking something like this would be used in simulation studies where often users condition on survival so maybe it'd be nice to have an argument that gives the option of doing that conditioning automatically. But I agree that just eliminating extinct trees gets rid of potentially useful information and would be something that should stay.
