### ISSUE TITLE
bad hybrid edge lengths when writing to Extended Newick format

### ISSUE THREAD

**Issue by fogg-uw** [jjustison/SiPhyNetwork#8]
Sometimes when using SiPhyNetwork::write.net to write the network to Extended Newick format, the hybrid edge lengths seem to come out wrong.  Specifically, here's an example in which 3 out of 4 hybrid edges have about 0.8752 added to what I believe their lengths ought to be.

```
library(SiPhyNetwork)

###

set.seed(1347) # current time
numbsim = 100
n = 7 # number of taxa to simulate to

###

inheritance.fxn <- make.beta.draw(1,1) # beta(1,1) distribution (i.e. unif(0,1))
hybrid_proportions <-c(0.5,  ##Lineage Generative
                       0.25, ##Lineage Degenerative
                       0.25) ##Lineage Neutral
ssa_nets <- sim.bdh.taxa.ssa(
  #age = age,
  n = 7,
  numbsim = numbsim,
  lambda=1, # speciation rate
  mu=0.2, # extinction rate
  nu=0.25, # hybridization rate,
  hybprops = hybrid_proportions,
  hyb.inher.fxn = inheritance.fxn,
  complete=FALSE
)

# i think this is correct (but doesn't include hybrid proportions)
ape::write.evonet(ssa_nets[[100]], 'sim100_evonet.tree') 

# i think this is incorrect in some of the hybrid edge lengths
SiPhyNetwork::write.net(ssa_nets[[100]], 'sim100_net.tree') 
```

**Comment by jjustison** [comment]
Thanks for the report!

This bug seems to stem from when writing a net, a conversion on edges is done such that the minor edges are always written as leaves. When doing this conversion I didn't make the appropriate swap of edge lengths.

In the process of fixing this and writing a test for it.

**Comment by jjustison** [comment]
This should be fixed now. Let me know if you run into any other issues. Thanks again!

**Comment by fogg-uw** [comment]
i checked the example above on my machine and it seems to be working OK.  thank you!
